// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func BaseLayoutTempl(content templ.Component, NavActive string, title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html class=\"h-full bg-gray-100\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><script src=\"https://cdn.tailwindcss.com\"></script><script src=\"/assets/js/htmx.min.js\"></script></head><body class=\"h-full page-loading\" hx-indicator=\"#loading-bar\"><style>\n          #loading-bar .particle{\n              opacity: 0;\n              position: fixed;\n              top: 0;\n              left: 0;\n              width: 100%;\n              height: 6px;\n              background: linear-gradient(90deg, transparent,\n                  #ffffff, transparent,\n                  #ffffff, transparent\n              );\n          }\n          .htmx-request#loading-bar,\n          .page-loading#loading-bar {\n            position: fixed;\n            top: 0;\n            bottom: 0;\n            left: 0;\n            right: 0;\n          }\n          .htmx-request#loading-bar .particle,\n          .page-loading#loading-bar .particle {\n              opacity: 1;\n              animation: fadeIn 2s linear infinite, slide 0.8s ease-in-out infinite;\n          }\n          @keyframes slide {\n              0%   { transform: translateX(-100%); }\n              100% { transform: translateX( 100%); }\n          }\n          @keyframes fadeIn {\n              0%   { opacity: 0; }\n              100% { opacity: 1; }\n          }\n      </style><div id=\"loading-bar\"><div class=\"particle\"></div></div><div id=\"errors\"></div><div class=\"min-h-full h-full grid grid-rows-[auto_1fr]\"><nav class=\"bg-black\"><div class=\"mx-auto max-w-7xl px-4 sm:px-6 lg:px-8\"><div class=\"flex h-16 items-center justify-between\"><div class=\"flex items-center\"><div class=\"md:hidden text-white font-bold text-xl\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout/base.templ`, Line: 56, Col: 74}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"hidden md:block\"><div class=\"ml-10 flex items-baseline space-x-4\"><!-- Current: \"bg-gray-900 text-white\", Default: \"text-gray-300 hover:bg-gray-700 hover:text-white\" -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if NavActive == "einkaufsliste" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"/\" class=\"rounded-md px-3 py-2 text-sm font-medium bg-gray-900 text-white\" aria-current=\"page\">Einkaufsliste</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"/\" class=\"rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white\">Einkaufsliste</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if NavActive == "rezepte" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"/rezepte\" class=\"rounded-md px-3 py-2 text-sm font-medium bg-gray-900 text-white\" aria-current=\"page\">Rezepte</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"/rezepte\" class=\"rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white\">Rezepte</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></div><div class=\"-mr-2 flex md:hidden\"><!-- Mobile menu button --><button id=\"mobile-menu-toggle\" type=\"button\" class=\"relative inline-flex items-center justify-center rounded-md bg-gray-800 p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800\" aria-controls=\"mobile-menu\" aria-expanded=\"false\"><span class=\"absolute -inset-0.5\"></span> <span class=\"sr-only\">Open main menu</span><!-- Menu open: \"hidden\", Menu closed: \"block\" --><svg class=\"block h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\" aria-hidden=\"true\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5\"></path></svg><!-- Menu open: \"block\", Menu closed: \"hidden\" --><svg class=\"hidden h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\" aria-hidden=\"true\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M6 18L18 6M6 6l12 12\"></path></svg></button></div></div></div><!-- Mobile menu, show/hide based on menu state. --><div class=\"hidden\" id=\"mobile-menu\"><div class=\"space-y-1 px-2 pb-3 pt-2 sm:px-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if NavActive == "einkaufsliste" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"/\" class=\"block rounded-md bg-gray-900 px-3 py-2 text-base font-medium text-white\" aria-current=\"page\">Einkaufsliste</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"/\" class=\"block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white\">Einkaufsliste</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if NavActive == "rezepte" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"/rezepte\" class=\"block rounded-md bg-gray-900 px-3 py-2 text-base font-medium text-white\" aria-current=\"page\">Rezepte</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"/rezepte\" class=\"block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white\">Rezepte</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></nav><main class=\"min-h-full w-full mx-auto px-4 py-2 sm:px-6 lg:px-8\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = content.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</main></div><script>\n      function setupErrorhandling() {\n          htmx.on('htmx:responseError', function(event) {\n            //TODO: transition in and out\n            const span = document.createElement(\"span\");\n            span.innerText = event.detail.xhr.response;\n            span.classList = \"fixed top-0 left-0 right-0 bg-red-500 text-white p-4 z-20\";\n            document.getElementById(\"errors\").append(span);\n            setTimeout(() => {\n              document.getElementById(\"errors\").removeChild(span);\n            }, 5000);\n          });\n      }\n      window.onbeforeunload = () => {\n        document.getElementById(\"loading-bar\").classList.add(\"page-loading\")\n      };\n      document.addEventListener(\"DOMContentLoaded\", ()=> {\n        document.getElementById(\"loading-bar\").classList.remove(\"page-loading\")\n        setupErrorhandling();\n      });\n      //TODO: cleanup\n      document.getElementById(\"mobile-menu-toggle\").onclick = function() {\n        //TODO: add transitions\n        document.getElementById(\"mobile-menu\").classList.toggle(\"hidden\");\n      };\n    </script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
